# Generated by Django 4.2 on 2023-05-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='units',
            new_name='type',
        ),
    ]
