# Generated by Django 4.2 on 2023-05-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_units_coursemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
