# Generated by Django 4.2 on 2023-05-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], max_length=8)),
                ('grade', models.CharField(choices=[('Grade 12', 'Grade 12'), ('Grade 11', 'Grade 11'), ('Grade 10', 'Grade 10'), ('Grade 9', 'Grade 9'), ('Grade 8', 'Grade 8')], max_length=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_courses', to='courses.coursemodel')),
            ],
            options={
                'verbose_name_plural': 'Students',
                'ordering': ['id'],
            },
        ),
    ]
