# Generated by Django 4.2 on 2023-05-02 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentmodel_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcoursesmodel',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentcoursesmodel',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.studentmodel'),
            preserve_default=False,
        ),
    ]
